### ISSUE TITLE
Baud Rates > 300

### ISSUE THREAD

**Issue by bozimmerman** [ChartreuseK/PETTERM#1]
Sorry for posting this as an issue, but I was unable to find other communication methods.

I read the source comments talking about the feasibility of baud rates > 300, but this was disabled.  I'm wondering if some other technical limitation was found?  300 baud is awfully hard to go back to once you've tasted  that sweet sweet 1200.  It's really preventing me from enjoying my PETs wifi modem. :(

**Comment by ChartreuseK** [comment]
The limitation is that of CPU time, there's not enough left to process the characters when the interrupt is being called at 3x the baud rate. Both the overhead of the interrupt handler and the fairly slow ANSI terminal emulation cause the issues. 

I haven't really had the time to work on this project for a while, but one approach I was looking at was to do the serial routine where the start bit is found by an interrupt (an extra jumper wire on the user port from the Rx pin to a pin that can trigger one) then more time is available for processing. I believe this is how most Vic-20 and C64 serial terminal programs handle it. As well as just general optimization.

**Comment by ChartreuseK** [comment]
Latest version 0.4.0 has a re-write of the serial routines making using of the interrupt line, allowing 600 and 1200 baud to work correctly, with the other code being optimized to allow this to work.
